[project]
name = "project-template"
version = "0.1.0"
description = "A copier uv template"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "copier>=9.11.3",
    "copier-templates-extensions>=0.3.2",
    "jinja2>=3.1.6",
    "python-slugify>=8.0.4",
]
